//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsSocket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApplicantDBEntities : DbContext
    {
        public ApplicantDBEntities()
            : base("name=ApplicantDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appool_applicant> appool_applicant { get; set; }
        public virtual DbSet<appool_booking> appool_booking { get; set; }
        public virtual DbSet<appool_checkin> appool_checkin { get; set; }
        public virtual DbSet<appool_ApplicantCheckIn> appool_ApplicantCheckIn { get; set; }
        public virtual DbSet<core_chat> core_chat { get; set; }
    
        public virtual int Sproc_AppoolCheckIn(string applicant_id, string purpose)
        {
            var applicant_idParameter = applicant_id != null ?
                new ObjectParameter("applicant_id", applicant_id) :
                new ObjectParameter("applicant_id", typeof(string));
    
            var purposeParameter = purpose != null ?
                new ObjectParameter("purpose", purpose) :
                new ObjectParameter("purpose", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sproc_AppoolCheckIn", applicant_idParameter, purposeParameter);
        }
    }
}
