//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsSocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appool_applicant
    {
        public string applicant_id { get; set; }
        public string empl_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public Nullable<System.DateTime> date_hired { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string tin { get; set; }
        public string sss { get; set; }
        public string gsis { get; set; }
        public string hdmf { get; set; }
        public string philhealth { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string citizenship { get; set; }
        public string religion { get; set; }
        public string sex { get; set; }
        public string civil_status { get; set; }
        public string blood_type { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string home_house_no { get; set; }
        public string home_street { get; set; }
        public string home_building { get; set; }
        public string home_barangay { get; set; }
        public string home_town { get; set; }
        public string home_province { get; set; }
        public string home_zip { get; set; }
        public string home_country { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string email_address { get; set; }
        public string applicant_status { get; set; }
        public string attachment { get; set; }
        public string contact_telno { get; set; }
        public string contact_celno { get; set; }
        public string howtheyknow { get; set; }
        public string posicode { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
        public string area { get; set; }
        public string persontosee { get; set; }
        public string describe_your_self { get; set; }
        public string skill { get; set; }
        public Nullable<bool> news_via_email { get; set; }
        public Nullable<bool> news_via_mobile { get; set; }
        public Nullable<byte> submitted_reqt { get; set; }
        public string remarks_reqt { get; set; }
        public int jobid { get; set; }
        public Nullable<byte> isacknowledge { get; set; }
        public string channel { get; set; }
        public Nullable<int> rating { get; set; }
        public string father_fname { get; set; }
        public string father_lname { get; set; }
        public Nullable<System.DateTime> father_bdate { get; set; }
        public string mother_fname { get; set; }
        public string mother_lname { get; set; }
        public Nullable<System.DateTime> mother_bdate { get; set; }
        public string birth_place { get; set; }
        public string nickname { get; set; }
        public string emergency_contact_person { get; set; }
        public string emergency_person_ralationship { get; set; }
        public string emergency_contact_number { get; set; }
        public string spouse_fname { get; set; }
        public string spouse_lname { get; set; }
        public Nullable<System.DateTime> spouse_bdate { get; set; }
    }
}
