//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsSocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appool_ApplicantCheckIn
    {
        public int login_id { get; set; }
        public string applicant_id { get; set; }
        public System.DateTime login_date { get; set; }
        public string purpose { get; set; }
        public string applicant_name { get; set; }
    }
}
