//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppsSocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appool_booking
    {
        public string applicant_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<System.TimeSpan> exam_time { get; set; }
        public string examiner { get; set; }
        public Nullable<int> exam_attend { get; set; }
        public Nullable<System.DateTime> exam_crea_date { get; set; }
        public string exam_crea_by { get; set; }
        public string exam_result1 { get; set; }
        public string exam_result2 { get; set; }
        public Nullable<byte> exam_passed { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public Nullable<System.TimeSpan> interview_time { get; set; }
        public string interviewer { get; set; }
        public Nullable<int> interview_attend { get; set; }
        public Nullable<System.DateTime> interview_crea_date { get; set; }
        public string interview_crea_by { get; set; }
        public Nullable<byte> interview_passed { get; set; }
        public string interview_result { get; set; }
    }
}
